### ISSUE TITLE
Add aem-tools actions support to stack manager

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-cloud#1]
The following actions are currently missing from stack-manager:
- export packages
- live snapshot
- offline snapshot
- offline compaction snapshot

**Comment by mbloch1986** [comment]
Added live snapshot

**Comment by mbloch1986** [comment]
Added export packages

**Comment by mbloch1986** [comment]
Done.

**Comment by mbloch1986** [comment]
Released with Stack Manager Cloud 1.1.0
