### ISSUE TITLE
Add new event to check environment readiness

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-cloud#21]
Given a stack prefix, Stack Manager should provide an event to check if the AEM environment is ready.

For Full-Set architecture, the check should be done on the Orchestrator instance.
For Consolidated architecture, the check should be done on the AuthorPublishDispatcher instance.

Yes, it's possible to run the check from Lambda, and yes, we can look at running Ruby AEM clients via Travelling Ruby, but the current design is to place the event logic within the architectures, and the Lambda function is currently used as a thin orchestration layer of the events. Moving the event logic should be applied to all events, and not just one of them (this will be a platform v3.x discussion).

**Comment by mbloch1986** [comment]
introduced in AEM AWS Stack Provisioner version 2.4.9
introduced in inspec aem aws version 0.9.0
