### ISSUE TITLE
Allow inexistent author-standby on full-set offline snapshot / compaction

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-cloud#28]
Currently offline snapshot and offline compaction snapshot on AEM Full-Set requires author-standby to exist.

However, we need to also consider the scenario where author-standby has been promoted to an author-primary following a termination of the original author-primary, which will then leave the environment with a single author-primary and no author-standby.

Offline snapshot and offline compaction snapshot events should identify an inexistent author-standby, log it, and then move on to the next step.

**Comment by mbloch1986** [comment]
Included in release 1.3.2
