### ISSUE TITLE
Suspend ASG Balancing when doing offline snapshots. 

### ISSUE THREAD

**Issue by hoomaan-kh** [shinesolutions/aem-stack-manager-cloud#45]
The offline snapshot will move one of the publish dispatchers instances to standby and at the same time take a snapshot from it.
The problem may happen when it takes a snapshot from AZ with a minimum number of Launched instance. like below example: 
AZa = 2 instance
AZb= 2 instance 
AZc= 1 instance
in this scenario, if we take a snapshot from an instance in AZc, the AutoScaling policy will apply AZ balancing, so it will remove one instance from AZa or AZb to add one instance to AZc.
to fix this issue we may need to suspend AZ balancing when we are doing the offline snapshot.

**Comment by mbloch1986** [comment]
Fix is to add  `AZrebalance` to the suspended/resume processes in the offline-snapshot lambda function
https://github.com/shinesolutions/aem-stack-manager-cloud/blob/master/lambda/aem_offline_snapshot.py#L200

**Comment by mbloch1986** [comment]
Included in release 1.9.1
