### ISSUE TITLE
AEM Stack Manager Silent Failures

### ISSUE THREAD

**Issue by Neko-Design** [shinesolutions/aem-stack-manager-cloud#50]
https://github.com/shinesolutions/aem-stack-manager-cloud/blob/5bfd611d9bb08c54e335ada97c87715896cf7f1d/lambda/aem_offline_snapshot.py#L305-L306

Hi All, When running the stack manager, our clients have occasionally experienced issues when IAM roles have been modified or VPC networking has been updated causing the Dynamo client to fail. The logs usually only print that a concurrent backup was attempted but hides the actual issue. We've updated our copy of the stack manager to log the actual error message here and it may be useful for others as well.

```python
except botocore.exceptions.ClientError as err:
    print("Error Updating Dynamo: {}".format(err))
    succeeded = False
```

**Comment by mbloch1986** [comment]
Thanks @Neko-Design for your suggestion. I raised a PR to add your suggestion.

**Comment by mbloch1986** [comment]
Integrated in release 2.0.0
