### ISSUE TITLE
Flush Dispatcher Cache action

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-cloud#9]
Need to add a new feature to `flush-dispatcher-cache`, which will execute deletion of all files under httpd docroot dir (e.g. `/var/www/html`) on publish-dispatcher instances .

**Comment by mbloch1986** [comment]
* own class for aem-tools dispatcher 
* docroot should be given as a parameter from the provisioner

**Comment by mbloch1986** [comment]
Done.

**Comment by mbloch1986** [comment]
Introduced in AEM Stack Manager Cloud version 1.2.0
introdced in AEM AWS Stack builder version 2.1.0
introduced in Puppet aem curator version 0.9.14
introduced in aem aws stack provisioner version 2.4.4
introduced in aem aws stack manager messenger version 1.2.0
